### PR TITLE
Update PurplePenExtractCourses.py

### PR DESCRIPTION
**Pull request by fbd38**
I did some modifications. Thansk a lot for the starting point.

### CODE REVIEW

**Comment by jmonclard** [comment]
Thanks for your addition.

- Please note that _newesttree = newtree_ on line 46 doesn't copy the tree but just create a new link on the same object. So removing nodes in _newestree_ actually remove them from _newtree_ !
Probably not what was intended...

- Repeating  _newestroot = newesttree.getroot()_ is probably useless

- Not so important : "Beacon" word should probably be replace by "Control"

**Comment by fbd38** [comment]
Hi Jmonclard,
(I do not know how this github stuff works)
Could you merge the code and transmit to Eric Pigeon, so that his 2021 Internship student could include this function in their server.
Regards,
Fbd38

**Comment by jmonclard** [comment]
OK, I will update my Python code with your changes after applying some fixes. (The normal process would have been you to fix your code and update your pull-request so I could merge it seamlessly, but I will do that myself this week-end).
I don't know Eric Pigeon, so please send him the link to this website once the code will be fixed.

**Comment by fbd38** [comment]
Tanks.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jmonclard** [comment]
Code merged.
I remove unnecessary portions of code.
Thanks for contributing.

**Pull request merged**
